### ISSUE TITLE
Stop polluting prototype with avers-specific functions

### ISSUE THREAD

**Issue by wereHamster** [wereHamster/avers-js#6]
Now that we've moved `aversProperties` to a private property and no longer expose it to users of the library, we should consider the same with event functions (`on`, `listenTo`, `trigger` etc).

We can expose the event functions through the `Avers` module. However, they create an `_events` property which is used to store callbacks that are attached to the object. What I have in mind is to store them in a `WeakMap` instead. It would probably have a small performance impact. Will need to benchmark it.

**Comment by wereHamster** [comment]
This is blocked until Chrome implements iterators or Map.prototype.forEach :(

**Comment by wereHamster** [comment]
Hm... the WeakMap trick might not be necessary after all. We could use the same private property mechanism like we used to hide `aversProperties`.

However, I'm not keen on changing that right now. The library works as it is now. I'll revisit this issue later.

**Comment by wereHamster** [comment]
As of f37a29e we do not attach any additional properties to your objects. Use `Avers.attach/detachChangeListener(obj, fn)` instead of `obj.on/off('change', fn)`.

**Comment by bstro** [comment]
Are you relying on ES6 WeakMaps or do you have some sort of implementation of it? I have read that WeakMaps are not possible to shim fully. I guess ultimately, because of your reliance on WeakMap, I cannot use your library without enabling experimental Javascript which severely limits the usability/transportability of the library.

**Comment by wereHamster** [comment]
Currently it relies on two ES6 features: `WeakMap` (used to track event callbacks) and `Symbol` (used to hide `aversProperties`). I actually planed to move everything over to `Symbol`, but didn't find the time yet. `Symbol` can be easily polyfilled.

I'm currently in the middle of nowhere (Nebraska, US) and will remain largely off-grid for the next two weeks. Maybe I'll find some time to do that, but if you want to give it a shot you can try.

A few notes to the event/listeners code. I originally copied it from backbone. But since avers only uses a single event (which is now internal, as you should use `Avers.attachChangeListener`), the code could be significantly simplified. That however could be done in a later step.
- Introduction to Symbol: http://webreflection.blogspot.com/2013/03/simulating-es6-symbols-in-es5.html
- Polyfill: https://github.com/medikoo/es6-symbol

**Comment by wereHamster** [comment]
Hah, I even added a comment to the code, see https://github.com/wereHamster/avers/blob/ead23cf28d57a8e170927050f0d9107f3fa097c7/avers.ts#L57-L58

**Comment by wereHamster** [comment]
@bstro, are you still interested in Avers? I can easily implement the required changes to remove the dependency on `WeakMap`.

**Comment by wereHamster** [comment]
As of 70aaacff7c88d6af81804abf9af7bccd5d5d8789, the dependency on `WeakMap` is gone. Only `Symbol` and `Object.observe` remain.
